//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

using System.Transactions;
using MySql.Data.MySqlClient;

using System.IO;
using System.Drawing;
using System.Drawing.Printing;

namespace PenjualanPembelian
{

    public class NotaJual
    {
        private string noNota;
        private DateTime tanggal;
        private Pelanggan pelanggan; // aggregation
        private Pegawai pegawai; // aggregation
        private List<NotaJualDetil> listNotaJualDetil; // composition

        #region CONSTRUCTORS
        public NotaJual()
        {
            this.NoNota = "";
            this.Tanggal = DateTime.Now;
            this.ListNotaJualDetil = new List<NotaJualDetil>();
        }
        public NotaJual(string pNoNota, DateTime pTanggal, Pelanggan pPelanggan, Pegawai pPegawai)
        {
            this.NoNota = pNoNota;
            this.Tanggal = pTanggal;
            this.Pelanggan = pPelanggan;
            this.Pegawai = pPegawai;
            this.ListNotaJualDetil = new List<NotaJualDetil>();
        }
        #endregion

        #region PROPERTIES
        public string NoNota
        {
            get { return noNota; }
            set { noNota = value; }
        }

        public DateTime Tanggal
        {
            get { return tanggal; }
            set { tanggal = value; }
        }

        public Pelanggan Pelanggan
        {
            get { return pelanggan; }
            set { pelanggan = value; }
        }

        public Pegawai Pegawai
        {
            get { return pegawai; }
            set { pegawai = value; }
        }

        public List<NotaJualDetil> ListNotaJualDetil
        {
            get { return listNotaJualDetil; }
            private set { listNotaJualDetil = value; } // composition, jadi tidak boleh diset di luar class
        }
        #endregion

        #region METHODS
        public void TambahDetilBarang(Barang pBarang, int pJumlah, int pHarga)
        {
            NotaJualDetil njd = new NotaJualDetil(pBarang, pJumlah, pHarga);
            this.ListNotaJualDetil.Add(njd);
        }

        public static string GenerateNoNota(out string pHasilNoNota)
        {
            // sql untuk mendapatkan nomor urut transaksi terakhir di tanggal hari ini (tanggal komputer)
            string sql = "SELECT SUBSTRING(NoNota, 9, 3) AS noUrutTransaksi " +
                         "FROM NotaJual WHERE Date(Tanggal) = Date(CURRENT_DATE) " +
                         "ORDER BY NoNota DESC LIMIT 1";

            pHasilNoNota = "";

            try
            {
                MySqlDataReader hasilData = Koneksi.JalankanPerintahQuery(sql);

                string noUrutTransTerbaru = "";

                if (hasilData.Read() == true)
                {
                    int noUrutTrans = int.Parse(hasilData.GetValue(0).ToString()) + 1;
                    noUrutTransTerbaru = noUrutTrans.ToString().PadLeft(3, '0'); // jika noUrutTrans < 3
                }
                else
                {
                    noUrutTransTerbaru = "001";
                }

                string tahun = DateTime.Now.Year.ToString();
                string bulan = DateTime.Now.Month.ToString().PadLeft(2, '0');
                string tanggal = DateTime.Now.Day.ToString().PadLeft(2, '0');

                pHasilNoNota = tahun + bulan + tanggal + noUrutTransTerbaru.ToString();

                return "1";
            }
            catch (Exception exc)
            {
                return exc.Message;
            }
        }

        public static string TambahData(NotaJual pNotaJual)
        {
            using (var tranScope = new TransactionScope(TransactionScopeOption.RequiresNew))
            {
                // tuliskan peritnah sql 1: menambahkan data nota ke tabel NotaJual
                string sql1 = "INSERT INTO NotaJual(NoNota, Tanggal, KodePelanggan, KodePegawai) VALUES ('" + pNotaJual.NoNota + "','" +
                               pNotaJual.Tanggal.ToString("yyyy-MM-dd hh:mm:ss") + "','" + pNotaJual.Pelanggan.KodePelanggan + "','" +
                               pNotaJual.Pegawai.KodePegawai + "')";

                try
                {
                    // jalankan perintah untuk menambahkan ke tabel NotaJual
                    Koneksi.JalankanPerintahDML(sql1);

                    //mendapatkan semua barang yg terjual dalam nota (nota jual detail)
                    for (int i = 0; i < pNotaJual.ListNotaJualDetil.Count; i++)
                    {
                        // perintah sql 2: menambahkan barang2 yg terjual ke tabel NotaJualDetil
                        string sql2 = "INSERT INTO NotaJualDetil(NoNota, KodeBarang, Harga, Jumlah) VALUES ('" + pNotaJual.NoNota + "','" +
                                      pNotaJual.ListNotaJualDetil[i].Barang.KodeBarang + "','" + pNotaJual.ListNotaJualDetil[i].Harga + "','" +
                                      pNotaJual.ListNotaJualDetil[i].Jumlah + "')";

                        Koneksi.JalankanPerintahDML(sql2);

                        string hasilUpdateBrg = Barang.UbahStokTerjual(pNotaJual.ListNotaJualDetil[i].Barang.KodeBarang, pNotaJual.ListNotaJualDetil[i].Jumlah);
                    }

                    // jika semua perintah DML berhasil dijalankan
                    tranScope.Complete();

                    return "1";
                }
                catch (Exception exc)
                {
                    tranScope.Dispose();

                    return exc.Message;
                }
            }
        }

        public static string BacaData(string pKriteria, string pNilaiKriteria, List<NotaJual> listHasilData)
        {
            string sql1 = "";
            if (pKriteria == "")
            {
                // tuliskan perintah SQL 1 : menampilkan semua data di tabel NotaJual
                sql1 = "SELECT N.NoNota, N.Tanggal, N.KodePelanggan, Plg.Nama AS NamaPelanggan, Plg.Alamat AS AlamatPelanggan, N.KodePegawai, Peg.Nama AS NamaPegawai " +
                       " FROM NotaJual N INNER JOIN Pelanggan Plg ON N.KodePelanggan = Plg.KodePelanggan " +
                       " INNER JOIN Pegawai Peg ON N.KodePegawai = Peg.KodePegawai " + 
                       " ORDER BY N.NoNota DESC";
            }
            else
            {
                sql1 = "SELECT N.NoNota, N.Tanggal, N.KodePelanggan, Plg.Nama AS NamaPelanggan, Plg.Alamat AS AlamatPelanggan, N.KodePegawai, Peg.Nama AS NamaPegawai " +
                       " FROM NotaJual N INNER JOIN Pelanggan Plg ON N.KodePelanggan = Plg.KodePelanggan " +
                       " INNER JOIN Pegawai Peg ON N.KodePegawai = Peg.KodePegawai " +
                       " WHERE " + pKriteria + " LIKE '%" + pNilaiKriteria + "%'" +
                       " ORDER BY N.NoNota DESC";
            }

            try
            {
                // Data reader 1 : memperoleh semua data di tabel NotaJual
                MySqlDataReader hasilData1 = Koneksi.JalankanPerintahQuery(sql1);
                listHasilData.Clear();
                while (hasilData1.Read() == true)
                {
                    // mendapatkan nomor nota jual dari hasil data reader
                    string nomorNota = hasilData1.GetValue(0).ToString();

                    // mendapatkan tanggal nota dari hasil data reader
                    DateTime tglNota = DateTime.Parse(hasilData1.GetValue(1).ToString());

                    // PELANGGAN yang melakukan transaksi
                    int kodePlg = int.Parse(hasilData1.GetValue(2).ToString());
                    string namaPlg = hasilData1.GetValue(3).ToString();
                    string alamatPlg = hasilData1.GetValue(4).ToString();
                       
                    // create objek bertipe Pelanggan
                    Pelanggan plg = new Pelanggan();
                    plg.KodePelanggan = kodePlg;
                    plg.Nama = namaPlg;
                    plg.Alamat = alamatPlg;

                    // PEGAWAI PEMBUAT NOTA
                    int kodePeg = int.Parse(hasilData1.GetValue(5).ToString());
                    string namaPeg = hasilData1.GetValue(6).ToString();

                    // create objek bertipe Pegawai
                    Pegawai peg = new Pegawai();
                    peg.KodePegawai = kodePeg;
                    peg.Nama = namaPeg;

                    // NOTA JUAL
                    NotaJual nota = new NotaJual(nomorNota, tglNota, plg, peg);

                    // query untuk mendapatkan detil nota jual dari tiap nota jual
                    // Perintah SQL 2 : mendapatkan barang yang ada di nota (dari tabel NotaJualDetil)
                    string sql2 = "SELECT NJD.KodeBarang, B.Nama, NJD.Harga, NJD.Jumlah " +
                                  "FROM NotaJual N INNER JOIN NotaJualDetil NJD ON N.NoNota = NJD.NoNota " +
                                  "INNER JOIN Barang B ON NJD.KodeBarang = B.KodeBarang " +
                                  "WHERE N.NoNota = '" + nomorNota + "'";

                    // Data reader 2 : memperoleh semua data barang nota di tabel NotaJualDetil
                    MySqlDataReader hasilData2 = Koneksi.JalankanPerintahQuery(sql2);

                    while (hasilData2.Read() == true)
                    {
                        // mendapatkan kode barang terjual
                        string kodeBrg = hasilData2.GetValue(0).ToString();
                        string namaBrg = hasilData2.GetValue(1).ToString();

                        Barang brg = new Barang();
                        brg.KodeBarang = kodeBrg;
                        brg.Nama = namaBrg;

                        // mendapatkan harga jual transaksi
                        int hrgJual = int.Parse(hasilData2.GetValue(2).ToString());
                        int jumlahJual = int.Parse(hasilData2.GetValue(3).ToString());

                        // create objek bertipe DetilNotaJual
                        NotaJualDetil detilNota = new NotaJualDetil(brg, jumlahJual, hrgJual);

                        // simpan detil barang ke nota
                        nota.TambahDetilBarang(brg, jumlahJual, hrgJual);
                    }

                    // simpan ke list
                    listHasilData.Add(nota);
                }
                return "1";
            }
            catch (MySqlException exc)
            {
                return exc.Message;
            }
        }

        public static string CetakNota(string pKriteria, string pNilaiKriteria, string pNamaFile)
        {
            try
            {
                List<NotaJual> listNotaJual = new List<NotaJual>();

                // baca data nota tertentu yang akan dicetak
                string hasilBaca = NotaJual.BacaData(pKriteria, pNilaiKriteria, listNotaJual);

                // simpan dulu isi nota yang akan ditampilkan ke objek file (StreamWrite)
                StreamWriter file = new StreamWriter(pNamaFile);

                for (int i = 0; i < listNotaJual.Count; i++)
                {
                    // tampilkan info perusahaan
                    file.WriteLine("");
                    file.WriteLine("TOKO MAJU MAKMUR UNTUNG SELALU");
                    file.WriteLine("Jl. Raya Kalirungkut Surabaya");
                    file.WriteLine("Telp. (031) - 12345678");
                    file.WriteLine("**".PadRight(50,'*'));

                    // tampilkan header nota
                    file.WriteLine("No.Nota : " + listNotaJual[i].NoNota);
                    file.WriteLine("Tanggal : " + listNotaJual[i].Tanggal);
                    file.WriteLine("");
                    file.WriteLine("Pelanggan : " + listNotaJual[i].Pelanggan.Nama);
                    file.WriteLine("Alamat : " + listNotaJual[i].Pelanggan.Alamat);
                    file.WriteLine("");
                    file.WriteLine("Kasir : " + listNotaJual[i].Pegawai.Nama);
                    file.WriteLine("=".PadRight(50, '='));

                    // tampilkan barang yang telah terjual
                    int grandTotal = 0; // untuk menyimpan grandTotal nota
                    for (int j = 0; j < listNotaJual[i].ListNotaJualDetil.Count; j++)
                    {
                        string nama = listNotaJual[i].ListNotaJualDetil[j].Barang.Nama;

                        // jika nama barang terlalu panjang maka hanya ambil 30 karakter pertama saja
                        if(nama.Length > 30)
                        {
                            nama = nama.Substring(0, 30);
                        }

                        int jumlah = listNotaJual[i].ListNotaJualDetil[j].Jumlah;
                        int harga = listNotaJual[i].ListNotaJualDetil[j].Harga;
                        int subTotal = jumlah * harga;

                        file.Write(nama.PadRight(30, ' '));
                        file.Write(jumlah.ToString().PadRight(3, ' '));
                        file.Write(harga.ToString("0,###").PadLeft(7, ' ')); // agar harga ditampilkan dengan pemisah ribuan
                        file.Write(subTotal.ToString("0,###").PadLeft(10, ' ')); // agar subTotal ditampilkan dengan pemisah riuan
                        file.WriteLine("");

                        // hitung grandTotal nota
                        grandTotal = grandTotal + jumlah * harga;
                    }

                    file.WriteLine("=".PadRight(50, '='));
                    file.WriteLine("TOTAL : " + grandTotal.ToString("0,###"));
                    file.WriteLine("=".PadRight(50, '='));
                    file.WriteLine("Terima Kasih Atas Kunjungan Anda");
                    file.WriteLine("");
                }
                file.Close();

                // cetak ke printer
                Cetak c = new Cetak(pNamaFile, "Courier New", 9, 10, 10, 10, 10);
                c.CetakKePrinter("tulisan");
                return "1";
            }
            catch (MySqlException exc)
            {
                return exc.Message;
            }
        }
        #endregion
    }
}