//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace PenjualanPembelian
{

    public class NotaJualDetil
    {
        private Barang barang; // aggregation
        private int jumlah;
        private int harga;

        #region CONSTRUCTORS
        public NotaJualDetil()
        {
            this.Jumlah = 1;
            this.Harga = 0;
        }
        public NotaJualDetil(Barang pBarang, int pJumlah, int pHarga)
        {
            this.Barang = pBarang;
            this.Jumlah = pJumlah;
            this.Harga = pHarga;
        }
        #endregion

        #region PROPERTIES
        public Barang Barang
        {
            get { return barang; }
            set { barang = value; }
        }

        public int Jumlah
        {
            get { return jumlah; }
            set { jumlah = value; }
        }

        public int Harga
        {
            get { return harga; }
            set { harga = value; }
        }
        #endregion
    }
}