//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

using MySql.Data.MySqlClient;

using System.IO;
using System.Drawing;
using System.Drawing.Printing;

namespace PenjualanPembelian
{
    public class Supplier
    {
        private int kodeSupplier;
        private string nama;
        private string alamat;

        #region CONSTRUCTORS
        public Supplier()
        {
            this.KodeSupplier = 0;
            this.Nama = "";
            this.Alamat = "";
        }

        public Supplier(int pKode, string pNama, string pAlamat)
        {
            this.KodeSupplier = pKode;
            this.Nama = pNama;
            this.Alamat = pAlamat;
        }
        #endregion

        #region PROPERTIES
        public int KodeSupplier
        {
            get { return kodeSupplier; }
            set { kodeSupplier = value; }
        }

        public string Nama
        {
            get { return nama; }
            set { nama = value; }
        }

        public string Alamat
        {
            get { return alamat; }
            set { alamat = value; }
        }
        #endregion

        #region METHODS
        public static string GenerateCode(out string pHasilId)
        {
            string sql = "SELECT COUNT(*) FROM supplier";
            pHasilId = "";

            try
            {
                MySqlDataReader hasilData = Koneksi.JalankanPerintahQuery(sql);

                if (hasilData.Read() == true)
                {
                    if (hasilData.GetValue(0).ToString() != "")
                    {
                        int idTerbaru = int.Parse(hasilData.GetValue(0).ToString()) + 1;

                        pHasilId = idTerbaru.ToString();
                    }
                    else
                    {
                        // Jika tidak ditemukan data dengan kategori tertentu maka kode terbaru = "J1"
                        pHasilId = "1";
                    }
                }
                return "1";
            }
            catch (Exception exc)
            {
                return exc.Message;
            }
        }

        public static string TambahData(Supplier sup)
        {
            string sql = "INSERT INTO supplier (KodeSupplier, Nama, Alamat) VALUES ('" + sup.KodeSupplier + "', '" + sup.Nama.Replace("'", "\\'") + "', '" + sup.Alamat + "')";

            try
            {
                Koneksi.JalankanPerintahDML(sql);
                return "1";
            }
            catch (MySqlException exc)
            {
                return exc.Message + ". Perintah SQL: " + sql;
            }
        }

        public static string BacaData(string kriteria, string nilaiKriteria, List<Supplier> listHasilData)
        {
            string sql = "";

            // JIka tidak ada kriteria yang diisikan
            if (kriteria == "")
            {
                sql = "SELECT * FROM supplier";
            }
            else
            {
                sql = "SELECT * FROM supplier WHERE " + kriteria + " LIKE '%" + nilaiKriteria + "%'";
            }

            try
            {
                MySqlDataReader hasilData = Koneksi.JalankanPerintahQuery(sql);

                while (hasilData.Read() == true) // selama masih ada data atau selama masih bisa membaca data
                {
                    // Baca hasil dari MySqlDataReader dan simpan di objek
                    Supplier sup = new Supplier();
                    sup.KodeSupplier = int.Parse(hasilData.GetValue(0).ToString());
                    sup.Nama = hasilData.GetValue(1).ToString();
                    sup.Alamat = hasilData.GetValue(2).ToString();

                    // Simpan ke list
                    listHasilData.Add(sup);
                }

                return "1";
            }
            catch (MySqlException exc)
            {
                return exc.Message + ". Perintah sql : " + sql;
            }
        }

        public static string UbahData(Supplier pSupplier)
        {
            string sql = "UPDATE supplier SET Nama = '" + pSupplier.Nama.Replace("'", "\\'") +
                         "', Alamat = '" + pSupplier.Alamat +
                         "' WHERE KodePegawai = '" + pSupplier.KodeSupplier + "'";

            try
            {
                Koneksi.JalankanPerintahDML(sql);
                return "1";
            }
            catch (MySqlException exc)
            {
                return exc.Message + ". Perintah sql : " + sql;
            }
        }

        public static string HapusData(Supplier pSupplier)
        {
            string sql = "DELETE FROM supplier WHERE KodeSupplier = '" + pSupplier.KodeSupplier + "'";

            try
            {
                Koneksi.JalankanPerintahDML(sql);
                return "1";
            }
            catch (MySqlException exc)
            {
                return exc.Message + ". Perintah sql : " + sql;
            }
        }

        public static string CetakNota(string pKriteria, string pNilaiKriteria, string pNamaFile)
        {
            try
            {
                List<Supplier> listSupplier = new List<Supplier>();

                // baca data nota tertentu yang akan dicetak
                string hasilBaca = Supplier.BacaData(pKriteria, pNilaiKriteria, listSupplier);

                // simpan dulu isi nota yang akan ditampilkan ke objek file (StreamWrite)
                StreamWriter file = new StreamWriter(pNamaFile);

                // tampilkan info perusahaan
                file.WriteLine("Laporan Per Tanggal : " + DateTime.Now.ToShortDateString());
                file.WriteLine("");
                file.WriteLine("TOKO MAJU MAKMUR UNTUNG SELALU");
                file.WriteLine("Jl. Raya Kalirungkut Surabaya");
                file.WriteLine("Telp. (031) - 12345678");
                file.WriteLine("**".PadRight(50, '*'));
                file.WriteLine("");

                for (int i = 0; i < listSupplier.Count; i++)
                {
                    // tampilkan header nota
                    file.WriteLine("Kode Supplier : " + listSupplier[i].KodeSupplier);
                    file.WriteLine("Nama : " + listSupplier[i].Nama);
                    file.WriteLine("Alamat : " + listSupplier[i].Alamat);
                    file.WriteLine("=".PadRight(50, '='));
                }
                file.Close();

                // cetak ke printer
                Cetak c = new Cetak(pNamaFile, "Courier New", 9, 10, 10, 10, 10);
                c.CetakKePrinter("tulisan");
                return "1";
            }
            catch (MySqlException exc)
            {
                return exc.Message;
            }
        }
        #endregion
    }
}